variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  SAST_EXCLUDED_ANALYZERS: "gosec-sast, eslint-sast, nodejs-scan-sast"

include:
  - template: Security/SAST.gitlab-ci.yml
  - project: 'templates/ci'
    file: 'DockerInDockerTemplate.yml'

stages:
  - test
  - build
  - release
  - notify
  - deploy

test:
  stage: test
  image: golang:latest
  script:
    - cd backend
    - go test -v ./...
  allow_failure: true

sonarqube-backend-sast:
  stage: test
  image: 
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  variables:
    GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - cd backend
    - >
      sonar-scanner
      -Dsonar.projectName=12_ИВАН_ШУБИН_MOMO_BACK
      -Dsonar.projectKey=go-momo-shubin-ivan
      -Dsonar.sources=.
      -Dsonar.host.url=${SONARQUBE_URL}
      -Dsonar.login=${SONAR_LOGIN_MOMO_BACK}
  allow_failure: true

build-backend:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}/backend"
      --dockerfile "${CI_PROJECT_DIR}/backend/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/momo-backend:${VERSION}"
  rules:
    - changes:
      - backend/**/*

upload-backend-latest:
  variables:
    GIT_STRATEGY: none
  image: docker:20.10.12-dind-rootless
  stage: release
  before_script:
    - until docker info; do sleep 1; done
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
  script:
    - docker pull $CI_REGISTRY_IMAGE/momo-backend:$VERSION
    - docker tag $CI_REGISTRY_IMAGE/momo-backend:$VERSION $CI_REGISTRY_IMAGE/momo-backend:latest
    - docker push $CI_REGISTRY_IMAGE/momo-backend:latest
  rules:
    - changes:
      - backend/**/*

deploy-helm:
  stage: deploy
  image:
    name: dtzar/helm-kubectl
    entrypoint: ['']
  script:
    - kubectl config get-contexts
    - kubectl config use-context std-012-042/momo-store:shubin-agent
    - helm repo add nexus ${NEXUS_REPO} --username ${NEXUS_USER} --password ${NEXUS_PASS}
    - helm repo update
    - >
      helm upgrade --install
      --namespace default
      --set global.dockerconfigjson=$DOCKERCONFIGJSON
      --set frontend.externalAddr=$MOMO_EXTERNAL_IP
      --set frontend.subnetId=$SUBNET_ID
      --set frontend.certId=$CERT_ID
      --atomic --timeout 15m
      momo-store nexus/momo-store
